In [ ]:
# Import libraries
from mpl_toolkits import mplot3d
import numpy as np
import matplotlib.pyplot as plt
# Creating dataset
x = np.outer(np.linspace(-3, 3, 2000), np.ones(2000))
y = x.copy().T # transpose
z = x**3+y**3-3*x-12*y+20
# Creating figure
fig = plt.figure(figsize =(15, 15))
ax = plt.axes(projection ='3d')
# Creating plot
ax.plot_surface(x, y, z)
# show plot
plt.show()


In [6]:

# derivative
import sympy
from sympy import Symbol , solve , Derivative , pprint
x= Symbol('x')
y= Symbol('y')
f=x**3+y**3-3*x-12*y+20
d1= Derivative (f , x ).doit ()
d2= Derivative (f , y ).doit ()
criticalpoints1 = solve( d1)
criticalpoints2 = solve( d2 )
print(' Solution set for x=',criticalpoints1,
'\n Solution set for y=', criticalpoints2)
s1= Derivative(f ,x , 2 ).doit()
s2= Derivative(f ,y , 2 ).doit()
s3= Derivative( Derivative(f , y ) ,x ) .doit()
q1=s1.subs({x: criticalpoints1[0], y: criticalpoints2[0]}).evalf ()
q2=s2.subs({x: criticalpoints1[0], y: criticalpoints2[0]}).evalf ()
q3=s3.subs({x: criticalpoints1[0], y: criticalpoints2[0]}).evalf ()
delta =q1*q2-q3 ** 2
if( delta >0 and q1<0 ):
    print("f takes Maximum value at",'(',criticalpoints1[0] ,',',criticalpoints2[0],')')
elif( delta >0 and q1>0 ):
    print(" f takes Minimum value at",'(',criticalpoints1[0] ,',',criticalpoints2[0],')')
if( delta <0 ):
    print ("The point is a saddle point at",'(',criticalpoints1[0],',',criticalpoints2[0],')' )
if( delta ==0 ):
    print(" Further tests required at",'(',criticalpoints1[0] ,',',criticalpoints2[0],')' )
f1=f.subs ({x: criticalpoints1[0],y: criticalpoints2[0]}).evalf()
print('Functional value is f(x,y)=',f1)


 Solution set for x= [-1, 1] 
 Solution set for y= [-2, 2]
f takes Maximum value at ( -1 , -2 )
Functional value is f(x,y)= 38.0000000000000


In [ ]:

#Gauss Sidel Method
import numpy as np
from scipy.linalg import solve

def Gauss_Seidel(A, B, x,n):
    L=np.tril(A)
    U=A-L
    counter =0
    print("Iteration\tX\tY\tZ")
    for i in range(n):
        x=np.dot(np.linalg.inv(L),B-np.dot(U,x))
        print(f"    {counter}\t",x)
        counter = counter+1
    return x

A=eval(input('Enter the matrix A:'))
B=eval(input('Enter the matrix B:'))
x=eval(input('Enter the guess  x: '))
n=eval(input('Enter the number of iterations: '))
x=Gauss_Seidel(A,B,x,n)
print('Solution using the solve syntax: \n',solve(A,B))    #np.array([[20,1,-2],[3,20,-1],[2,-3,20]])  [17,-18,25]  [0,0,0]  25

In [ ]:
    
#solve derivative
from sympy import *
from IPython.display import display

x, y = symbols('x y')
y = Function('y')(x)
y1 = Derivative(y, x)
eq = x**3 * y1 - x**2 * y + y**4 * cos(x)
z1 = dsolve(eq, y)
display(z1)



[Eq(y(x), (x**3/(C1 + 3*sin(x)))**(1/3)),
 Eq(y(x), (x**3/(C1 + 3*sin(x)))**(1/3)*(-1 - sqrt(3)*I)/2),
 Eq(y(x), (x**3/(C1 + 3*sin(x)))**(1/3)*(-1 + sqrt(3)*I)/2)]

In [ ]:
#graph
import numpy as np
from scipy . integrate import odeint
import matplotlib . pyplot as plt
def model (y,t):
    k=0.3
    return -k*y
y0=5
t=np. linspace (0,20)
y= odeint (model ,y0 ,t)
plt . plot (t,y)
plt . title ('Solution of dy/dt=-ky; k=0.3, y(0)=5')
plt . xlabel ('time ')
plt . ylabel ('y(t)')
plt . show ()

In [1]:
#Eigen Values and Eigen Vectors

import numpy as np 
I=np. array ([[6,-2,2],[-2,3,-1],[2,-1 ,3]]) 
print ("\n Given matrix : \n", I) 
w,v = np.linalg.eig(I)
print ("\n Eigen values : \n", w)
print ("\n Eigen vectors : \n", v) 
## To display one eigen value and corresponding eigen vector 
for i in range(3): 
    print (" Eigen value :\n ", w[i]) 
    print ("\n Corresponding Eigen vector :", v[:,i])


 Given matrix : 
 [[ 6 -2  2]
 [-2  3 -1]
 [ 2 -1  3]]

 Eigen values : 
 [8. 2. 2.]

 Eigen vectors : 
 [[ 0.81649658 -0.57735027 -0.11547005]
 [-0.40824829 -0.57735027  0.57735027]
 [ 0.40824829  0.57735027  0.80829038]]
 Eigen value :
  7.999999999999999

 Corresponding Eigen vector : [ 0.81649658 -0.40824829  0.40824829]
 Eigen value :
  1.9999999999999982

 Corresponding Eigen vector : [-0.57735027 -0.57735027  0.57735027]
 Eigen value :
  2.0

 Corresponding Eigen vector : [-0.11547005  0.57735027  0.80829038]


: 

In [2]:
x=1.532
print(type(x))

<class 'float'>
